import { BlogPost } from './blog-service';

export const STATIC_BLOG_POSTS: BlogPost[] = [
    {
        id: 'static-ai-writer',
        slug: 'ai-writer-for-marketing',
        title: 'AI Writer for Marketing: La Guía Definitiva para Redactores Digitales',
        excerpt: 'Domina el AI writer for marketing con nuestra guía completa. Técnicas, herramientas y estrategias para crear contenido que convierte.',
        content: '', // Not needed for list view
        category: 'Inteligencia Artificial',
        author: 'Selamu',
        readTime: '8 min',
        tags: ['Marketing', 'IA', 'Copywriting'],
        image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&q=80&w=1000',
        featured: true,
        trending: true,
        views: 1250,
        likes: 145,
        publishedAt: '2025-01-27T10:00:00Z',
    },
    {
        id: 'static-chatgpt-writers',
        slug: 'chatgpt-para-escritores',
        title: 'ChatGPT para Escritores: Cómo Potenciar tu Creatividad',
        excerpt: 'Guía práctica para escritores sobre cómo usar ChatGPT como asistente creativo. Prompts, técnicas de edición y mejores prácticas.',
        content: '',
        category: 'Creatividad',
        author: 'Selamu',
        readTime: '12 min',
        tags: ['ChatGPT', 'Escritura', 'Prompts'],
        image: 'https://images.unsplash.com/photo-1694056263595-c266a2cb1e30?q=80&w=1000&auto=format&fit=crop',
        featured: true,
        trending: false,
        views: 980,
        likes: 89,
        publishedAt: '2025-02-05T10:00:00Z',
    },
    {
        id: 'static-copywriting-ia',
        slug: 'copywriting-con-inteligencia-artificial',
        title: 'Copywriting con Inteligencia Artificial: Textos Persuasivos en Minutos',
        excerpt: 'Domina el arte del copywriting asistido por IA. Cómo crear landing pages, anuncios y textos de venta que convierten.',
        content: '',
        category: 'Copywriting',
        author: 'Selamu',
        readTime: '14 min',
        tags: ['Copywriting', 'Ventas', 'Conversión'],
        image: 'https://images.unsplash.com/photo-1664575602554-208c7a264381?q=80&w=1000&auto=format&fit=crop',
        featured: false,
        trending: true,
        views: 850,
        likes: 67,
        publishedAt: '2025-02-15T10:00:00Z',
    },
    {
        id: 'static-generador-contenido',
        slug: 'generador-contenido-ia-marketing-digital-2025',
        title: 'Cómo los Generadores de Contenido IA Revolucionan el Marketing Digital',
        excerpt: 'Descubre cómo la IA está transformando la creación de contenido en 2025. Herramientas, tendencias y predicciones.',
        content: '',
        category: 'Marketing Digital',
        author: 'Red Creativa Pro',
        readTime: '10 min',
        tags: ['Marketing Digital', 'Tendencias', '2025'],
        image: 'https://images.unsplash.com/photo-1633419461186-7d40a239337d?auto=format&fit=crop&q=80&w=1000',
        featured: false,
        trending: false,
        views: 450,
        likes: 32,
        publishedAt: '2025-01-20T10:00:00Z',
    },
    {
        id: 'static-prompts-escritura',
        slug: 'mejores-prompts-ia-escritura',
        title: 'Mejores Prompts para IA de Escritura: 100 Plantillas que Funcionan',
        excerpt: 'Plantillas probadas que mejoran la calidad de tu contenido generado. Copy-paste para ChatGPT, Claude y más.',
        content: '',
        category: 'Prompts',
        author: 'Red Creativa Pro',
        readTime: '15 min',
        tags: ['Prompts', 'Productividad', 'Guías'],
        image: 'https://images.unsplash.com/photo-1684369175836-5ae1c81216d1?auto=format&fit=crop&q=80&w=1000',
        featured: false,
        trending: false,
        views: 2100,
        likes: 340,
        publishedAt: '2025-01-15T10:00:00Z',
    }
];
