version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redcreativapro2
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    # Load environment variables from .env if available
    env_file:
      - .env
