@echo off
echo Arreglando problema de ChunkLoadError...

echo 1. Deteniendo servidor de desarrollo...
taskkill /f /im node.exe 2>nul

echo 2. Limpiando cache de Next.js...
if exist .next rmdir /s /q .next
if exist node_modules\.cache rmdir /s /q node_modules\.cache

echo 3. Limpiando cache de npm...
npm cache clean --force

echo 4. Reinstalando dependencias criticas...
npm install next@latest react@latest react-dom@latest

echo 5. Reiniciando servidor...
start cmd /k "npm run dev"

echo ✅ Problema de ChunkLoadError solucionado
echo El servidor se esta reiniciando en una nueva ventana...
pause