import { BlogPost } from './blog-data'

export interface InternalLink {
  id: string
  sourcePageId: string
  targetPageId: string
  anchorText: string
  contextBefore: string
  contextAfter: string
  relevanceScore: number
  position: number
  isAutoGenerated: boolean
  createdAt: string
  updatedAt: string
}

export interface LinkSuggestion {
  targetPageId: string
  targetUrl: string
  targetTitle: string
  anchorText: string
  relevanceScore: number
  reason: string
  contextMatch: string
}

export interface PageLinkProfile {
  pageId: string
  internalLinksOut: number
  internalLinksIn: number
  linkDensity: number
  averageRelevanceScore: number
  orphanStatus: boolean
  hubScore: number
}

export class InternalLinkingService {
  private blogPosts: BlogPost[]
  private sitePages: Array<{
    id: string
    title: string
    url: string
    content?: string
    category?: string
    tags?: string[]
    priority: number
  }>

  constructor(blogPosts: BlogPost[]) {
    this.blogPosts = blogPosts
    this.sitePages = this.initializeSitePages()
  }

  private initializeSitePages() {
    // Define main site pages with their priorities and categories
    return [
      {
        id: 'home',
        title: 'Red Creativa Pro - Herramientas IA para Creativos',
        url: '/',
        category: 'main',
        tags: ['ia', 'creatividad', 'herramientas', 'productividad'],
        priority: 1.0
      },
      {
        id: 'escritor-ia',
        title: 'Escritor IA - Generador de Contenido Inteligente',
        url: '/escritor-ia',
        category: 'tools',
        tags: ['escritura', 'ia', 'contenido', 'redaccion'],
        priority: 0.95
      },
      {
        id: 'correos-ia',
        title: 'Correos IA - Generador de Emails Inteligente',
        url: '/correos-ia',
        category: 'tools',
        tags: ['email', 'marketing', 'ia', 'automatizacion'],
        priority: 0.95
      },
      {
        id: 'seo-dashboard',
        title: 'SEO Dashboard - Optimización Inteligente',
        url: '/seo-dashboard',
        category: 'tools',
        tags: ['seo', 'optimizacion', 'analytics', 'ia'],
        priority: 0.9
      },
      {
        id: 'dashboard',
        title: 'Dashboard - Panel de Control',
        url: '/dashboard',
        category: 'app',
        tags: ['dashboard', 'control', 'gestion'],
        priority: 0.9
      },
      {
        id: 'blog',
        title: 'Blog - Artículos sobre IA y Creatividad',
        url: '/blog',
        category: 'content',
        tags: ['blog', 'articulos', 'ia', 'creatividad'],
        priority: 0.9
      },
      {
        id: 'planes',
        title: 'Planes y Precios - Suscripciones',
        url: '/planes',
        category: 'commercial',
        tags: ['planes', 'precios', 'suscripcion'],
        priority: 0.9
      }
    ]
  }

  /**
   * Generate contextual internal link suggestions for a given page
   */
  generateLinkSuggestions(
    sourcePageId: string,
    content: string,
    maxSuggestions: number = 5
  ): LinkSuggestion[] {
    const suggestions: LinkSuggestion[] = []
    const sourceContent = content.toLowerCase()
    
    // Get all potential target pages (excluding source)
    const allPages = [
      ...this.sitePages.map(page => ({
        ...page,
        type: 'page' as const
      })),
      ...this.blogPosts.map(post => ({
        id: post.id,
        title: post.title,
        url: `/blog/${post.id}`,
        category: post.category,
        tags: post.tags,
        priority: this.calculateBlogPostPriority(post),
        type: 'blog' as const,
        content: post.content
      }))
    ].filter(page => page.id !== sourcePageId)

    // Analyze each potential target page
    for (const targetPage of allPages) {
      const relevanceScore = this.calculateRelevanceScore(
        sourceContent,
        targetPage,
        sourcePageId
      )

      if (relevanceScore > 0.3) { // Minimum relevance threshold
        const anchorText = this.generateAnchorText(targetPage, sourceContent)
        const contextMatch = this.findBestContextMatch(sourceContent, targetPage)

        suggestions.push({
          targetPageId: targetPage.id,
          targetUrl: targetPage.url,
          targetTitle: targetPage.title,
          anchorText,
          relevanceScore,
          reason: this.generateLinkReason(targetPage, relevanceScore),
          contextMatch
        })
      }
    }

    // Sort by relevance score and return top suggestions
    return suggestions
      .sort((a, b) => b.relevanceScore - a.relevanceScore)
      .slice(0, maxSuggestions)
  }

  /**
   * Calculate relevance score between source content and target page
   */
  private calculateRelevanceScore(
    sourceContent: string,
    targetPage: any,
    sourcePageId: string
  ): number {
    let score = 0

    // Tag overlap scoring
    const sourceWords = sourceContent.split(/\s+/)
    const targetTags = targetPage.tags || []
    
    for (const tag of targetTags) {
      const tagWords = tag.toLowerCase().split(/[-\s]+/)
      for (const tagWord of tagWords) {
        if (sourceContent.includes(tagWord)) {
          score += 0.2
        }
      }
    }

    // Title keyword matching
    const titleWords = targetPage.title.toLowerCase().split(/\s+/)
    for (const word of titleWords) {
      if (word.length > 3 && sourceContent.includes(word)) {
        score += 0.15
      }
    }

    // Category relevance
    if (targetPage.category) {
      const categoryWords = targetPage.category.toLowerCase().split(/[-\s]+/)
      for (const word of categoryWords) {
        if (sourceContent.includes(word)) {
          score += 0.1
        }
      }
    }

    // Content similarity (for blog posts)
    if (targetPage.content) {
      const targetContent = targetPage.content.toLowerCase()
      const commonWords = this.findCommonKeywords(sourceContent, targetContent)
      score += commonWords.length * 0.05
    }

    // Priority boost for high-priority pages
    score *= targetPage.priority

    return Math.min(score, 1.0) // Cap at 1.0
  }

  /**
   * Generate appropriate anchor text for a link
   */
  private generateAnchorText(targetPage: any, sourceContent: string): string {
    const title = targetPage.title
    const tags = targetPage.tags || []

    // Try to find natural anchor text in source content
    const titleWords = title.toLowerCase().split(/\s+/)
    const mainKeyword = titleWords.find(word => 
      word.length > 4 && sourceContent.includes(word)
    )

    if (mainKeyword) {
      // Find the most relevant phrase containing the keyword
      const sentences = sourceContent.split(/[.!?]+/)
      for (const sentence of sentences) {
        if (sentence.includes(mainKeyword)) {
          const words = sentence.trim().split(/\s+/)
          const keywordIndex = words.findIndex(word => 
            word.toLowerCase().includes(mainKeyword)
          )
          
          if (keywordIndex !== -1) {
            // Extract 2-4 words around the keyword
            const start = Math.max(0, keywordIndex - 1)
            const end = Math.min(words.length, keywordIndex + 3)
            const phrase = words.slice(start, end).join(' ')
            
            if (phrase.length > 10 && phrase.length < 60) {
              return phrase.trim()
            }
          }
        }
      }
    }

    // Fallback to title or main tag
    if (title.length < 60) {
      return title
    }

    return tags[0] || title.substring(0, 50) + '...'
  }

  /**
   * Find common keywords between two pieces of content
   */
  private findCommonKeywords(content1: string, content2: string): string[] {
    const words1 = content1.toLowerCase().match(/\b\w{4,}\b/g) || []
    const words2 = content2.toLowerCase().match(/\b\w{4,}\b/g) || []
    
    const commonWords = words1.filter(word => 
      (words2 as string[]).includes(word) && 
      !this.isStopWord(word)
    )

    return [...new Set(commonWords)] // Remove duplicates
  }

  /**
   * Check if a word is a stop word
   */
  private isStopWord(word: string): boolean {
    const stopWords = [
      'para', 'con', 'por', 'como', 'que', 'una', 'del', 'las', 'los',
      'esta', 'este', 'son', 'más', 'todo', 'pero', 'sus', 'muy',
      'the', 'and', 'for', 'are', 'but', 'not', 'you', 'all', 'can'
    ]
    return stopWords.includes(word.toLowerCase())
  }

  /**
   * Calculate priority for blog posts based on metrics
   */
  private calculateBlogPostPriority(post: BlogPost): number {
    let priority = 0.6 // Base priority for blog posts

    if (post.featured) priority += 0.15
    if (post.trending) priority += 0.1
    if ((post.views || 0) > 3000) priority += 0.1
    if ((post.views || 0) > 5000) priority += 0.05

    return Math.min(priority, 0.85) // Cap at 0.85 for blog posts
  }

  /**
   * Generate reason for link suggestion
   */
  private generateLinkReason(targetPage: any, relevanceScore: number): string {
    if (relevanceScore > 0.8) {
      return 'Altamente relevante - contenido muy relacionado'
    } else if (relevanceScore > 0.6) {
      return 'Relevante - temas complementarios'
    } else if (relevanceScore > 0.4) {
      return 'Moderadamente relevante - contexto relacionado'
    } else {
      return 'Relevancia básica - puede ser útil para el usuario'
    }
  }

  /**
   * Find best context match for link placement
   */
  private findBestContextMatch(sourceContent: string, targetPage: any): string {
    const sentences = sourceContent.split(/[.!?]+/)
    const targetKeywords = [
      ...targetPage.title.toLowerCase().split(/\s+/),
      ...(targetPage.tags || []).join(' ').toLowerCase().split(/\s+/)
    ].filter(word => word.length > 3)

    let bestMatch = ''
    let maxMatches = 0

    for (const sentence of sentences) {
      const sentenceLower = sentence.toLowerCase()
      const matches = targetKeywords.filter(keyword => 
        sentenceLower.includes(keyword)
      ).length

      if (matches > maxMatches) {
        maxMatches = matches
        bestMatch = sentence.trim()
      }
    }

    return bestMatch.substring(0, 200) + (bestMatch.length > 200 ? '...' : '')
  }

  /**
   * Analyze page link profile for SEO optimization
   */
  analyzePageLinkProfile(pageId: string, existingLinks: InternalLink[]): PageLinkProfile {
    const outgoingLinks = existingLinks.filter(link => link.sourcePageId === pageId)
    const incomingLinks = existingLinks.filter(link => link.targetPageId === pageId)

    const averageRelevanceScore = outgoingLinks.length > 0
      ? outgoingLinks.reduce((sum, link) => sum + link.relevanceScore, 0) / outgoingLinks.length
      : 0

    // Calculate hub score (pages that link to many relevant pages)
    const hubScore = this.calculateHubScore(outgoingLinks)

    return {
      pageId,
      internalLinksOut: outgoingLinks.length,
      internalLinksIn: incomingLinks.length,
      linkDensity: this.calculateLinkDensity(pageId, outgoingLinks.length),
      averageRelevanceScore,
      orphanStatus: incomingLinks.length === 0 && pageId !== 'home',
      hubScore
    }
  }

  /**
   * Calculate link density for a page
   */
  private calculateLinkDensity(pageId: string, linkCount: number): number {
    // Estimate content length based on page type
    const page = this.sitePages.find(p => p.id === pageId) || 
                 this.blogPosts.find(p => p.id === pageId)
    
    if (!page) return 0

    const estimatedWordCount = page.content 
      ? page.content.split(/\s+/).length 
      : 500 // Default estimate

    return linkCount / (estimatedWordCount / 100) // Links per 100 words
  }

  /**
   * Calculate hub score for a page
   */
  private calculateHubScore(outgoingLinks: InternalLink[]): number {
    if (outgoingLinks.length === 0) return 0

    const relevanceSum = outgoingLinks.reduce((sum, link) => sum + link.relevanceScore, 0)
    const diversityBonus = new Set(outgoingLinks.map(link => link.targetPageId)).size / outgoingLinks.length

    return (relevanceSum / outgoingLinks.length) * diversityBonus
  }

  /**
   * Generate automated internal links for content
   */
  generateAutomatedLinks(
    pageId: string,
    content: string,
    maxLinks: number = 3
  ): Array<{
    position: number
    anchorText: string
    targetUrl: string
    targetTitle: string
  }> {
    const suggestions = this.generateLinkSuggestions(pageId, content, maxLinks * 2)
    const automatedLinks: Array<{
      position: number
      anchorText: string
      targetUrl: string
      targetTitle: string
    }> = []

    const contentWords = content.split(/\s+/)
    let linksAdded = 0

    for (const suggestion of suggestions) {
      if (linksAdded >= maxLinks) break

      // Find optimal position for the link
      const anchorWords = suggestion.anchorText.toLowerCase().split(/\s+/)
      const firstAnchorWord = anchorWords[0]

      for (let i = 0; i < contentWords.length - anchorWords.length + 1; i++) {
        const wordSequence = contentWords.slice(i, i + anchorWords.length)
          .join(' ').toLowerCase()

        if (wordSequence.includes(firstAnchorWord)) {
          // Check if this position is not too close to existing links
          const tooClose = automatedLinks.some(link => 
            Math.abs(link.position - i) < 50 // Minimum 50 words between links
          )

          if (!tooClose) {
            automatedLinks.push({
              position: i,
              anchorText: suggestion.anchorText,
              targetUrl: suggestion.targetUrl,
              targetTitle: suggestion.targetTitle
            })
            linksAdded++
            break
          }
        }
      }
    }

    return automatedLinks.sort((a, b) => a.position - b.position)
  }
}